[package]
name = "audio_collab"
version = "0.1.0"
edition = "2021"


[dependencies]
vizia = {git = "https://github.com/vizia/vizia", branch = "textbox-dev"}
ron = "0.7"
serde = { version = "1", features = ["derive"] }